# Generated by Django 5.0.14 on 2025-08-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skillcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills_category_images/'),
        ),
    ]
