# Generated by Django 5.0.14 on 2025-08-08 06:34

import apps.skills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.skills.models.skills_upload_to),
        ),
    ]
